mahmoud/awesome-python-applications

projects.yaml

**Application name**: Beets
**Application repo link**: https://github.com/beetbox/beets
**Application home link**: http://beets.io
**Application description**: music library manager and MusicBrainz tagger

Add project: Beets

---

projects.yaml

**Application name**: pipenv
**Application repo link**: https://github.com/pypa/pipenv
**Application home link**: https://pipenv.readthedocs.io/en/latest/
**Application description**: Python Development Workflow for Humans
**Jannis Leidel**, former pip maintainerâ€”
*Pipenv is the porcelain I always wanted to build for pip. It fits my brain and mostly replaces virtualenvwrapper and manual pip calls for me. Use it.*
**David Gang**
*This …

Add project: pipenv on Package management section

---

README.md
projects.yaml

**Application name**: streamlink
**Application repo link**: https://github.com/streamlink/streamlink
**Application home link**: https://streamlink.github.io/
**Application description**: Command-line utility that extracts streams from various services and pipes them into a video player of choice.
Streamlink is a CLI utility that pipes flash videos from online streaming services to a variety of video players such as VLC.
The main purpose …

Add project: Streamlink

---

projects.yaml

**Application name**: OPEM
**Application repo link**: https://github.com/ECSIM/opem
**Application home link**:  https://www.ecsim.ir/opem/
**Application description**: The Open-Source PEMFC Simulation Tool (OPEM) is a modeling tool for evaluating the performance of proton exchange membrane fuel cells. This package is a combination of models (static/dynamic) that predict the optimum operating parameters of PEMFC. OPEM contained generic models that will accept as input, not only values of the operating variables such as anode and cathode feed gas, pressure and compositions, cell temperature and current density, but also cell parameters including the active area and membrane thickness. In addition, some of the different models of PEMFC that have been proposed in the OPEM, just focus on one …

Add project: OPEM

---

apatite/apatite/cli.py
apatite/apatite/metrics/license.py

Let's add some automatic detection of licenses to the APA.

Automated License Detection

---

apatite/apatite/cli.py
apatite/apatite/dal.py
apatite/apatite/metrics/gh.py
apatite/apatite/metrics/license.py
apatite/apatite/metrics/vcs.py

Adds two main features:
- support for required env variables
- github collect-metrics module
Notes to reviewer:
Not happy about the DAL extensions I made, would like to hear any suggestions of how to better structure it.
Any comments on the use of curl would be appreciated too. Might be some benefit to using another lib like requests?

Simple Github Metric Support

---

apatite/apatite/dal.py
projects.yaml

This PR adds the behavior of stripping trailing slashes during normalization of project.yaml

Strip URL Trailing Slashes during Normalization

---

apatite/apatite/dal.py
projects.yaml

This is WIP until the automation-fix-yaml PR merges.
If it doesn't merge then close this, it's based off of automation-fix-yaml

WIP: Fix Planets Link

---

projects.yaml

Add privacyIDEA

---

projects.yaml

**Application name**: doit
**Application repo link**: https://github.com/pydoit/doit
**Application home link**: https://pydoit.org/
**Application description**: Task management & automation tool.
- The nikola static site generator on this awesome list uses it for builds.

Add project: doit

---

CONTRIBUTING.md
TODO.md

This is a meta-PR, rather than an application-specific one.
It fixes a couple of typos in the text.

Fix a typo and a spelling mistake

---

projects.yaml

**Application name**: Airflow
**Application repo link**: https://github.com/apache/airflow/
**Application home link**: https://airflow.apache.org/
**Application description**: Airflow is a platform to programmatically author, schedule and monitor workflows. 
closes #116

Add Project: Airflow

---

TODO.md

Update TODO.md - Small typo

---

projects.yaml

Added Wikipedia references to 
- Deluge
- Lutris
- PyChess
- Autokey
- Calibre
- Gedit
- Jupyter Notebook (sort of - it's a paragraph in the Project Jupyter page)
- Komodo Edit
- Leo Editor
- Spyder IDE

Update projects.yaml - Wikipedia references to 10 projects

---

projects.yaml

resolves #109 
**Application name**: hosts
**Application repo link**: [https://github.com/StevenBlack/hosts](https://github.com/StevenBlack/hosts)
**Application description**: The purpose of this project is to consolidate several reputable `hosts` files, and merges them into a unified hosts file with duplicates removed for the purpose of blocking undesirable websites via DNS blackhole.  One can optionally invoke extensions to block additional sites by category.   …

Adds the hosts project

---

projects.yaml

Add project: pip-tools

---

projects.yaml

**Application name**: Nuxeo Drive
**Application repo link**: https://github.com/nuxeo/nuxeo-drive
**Application home link**: https://www.nuxeo.com/products/drive-desktop-sync/
**Application description**: Cross-platform desktop synchronization client for the Nuxeo platform.
-> Hard to ship a full application on PyPi :) But the app is using the home made Python SDK, which is available on PyPi (https://pypi.org/project/nuxeo/).
I think …

Add project: Nuxeo Drive

---

projects.yaml

**Application name**: paperless
**Application repo link**: https://github.com/the-paperless-project/paperless
**Application home link**:
**Application description**: Scan, index, and archive all of your paper documents 
Paperless helps automating archival of actual paper documents. It supports receiving documents via email (among others) so it integrates very well with scanners which can send scanned documents over the network. It runs …

Add project: paperless

---

BY_PLATFORM.md
README.md
atom.xml
projects.yaml

**Application name**: Recon-ng
**Application repo link**:  https://github.com/lanmaster53/recon-ng
**Application home link**: https://github.com/lanmaster53/recon-ng
**Application description**: Recon-ng provides a powerful environment to conduct open source web-based reconnaissance quickly and thoroughly.
It is an application even though the online description mentions "framework"
Recon-ng has a pip installer …

"Add project: Recon-ng"

---

.github/workflows/workflow.yml

I heard you talking about this project on Talk Python to Me and you mentioned how much of a hassle it is to check all the links for 404s, and it inspired me to create a GitHub action to help with the process. It definitely could still use work, but I thought it was a start and would help weed out the known 200s.

Github action that checks links

---

BY_PLATFORM.md
README.md
atom.xml
projects.yaml

**Application name**: mycli
**Application repo link**: https://github.com/dbcli/mycli
**Application home link**: https://www.mycli.net/
**Application description**: Interactive MySQL client that does auto-completion and syntax highlighting. 
Its sister project that is pgcli is already in the list, mycli is basically pgcli for MySQL.

adding mycli
